src/Entity/Course.php
<?php

namespace App\Entity;

use App\Entity\Session;
use App\Entity\Document;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CourseRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=CourseRepository::class)
 */
class Course
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $course_name;

    /**
     * @ORM\OneToMany(targetEntity=Session::class, mappedBy="course")
     */
    private $session;

    /**
     * @ORM\ManyToMany(targetEntity=document::class, inversedBy="courses")
     */
    private $document;

    public function __construct()
    {
        $this->session = new ArrayCollection();
        $this->document = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCourseName(): ?string
    {
        return $this->course_name;
    }

    public function setCourseName(string $course_name): self
    {
        $this->course_name = $course_name;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSession(): Collection
    {
        return $this->session;
    }

    public function addSession(Session $session): self
    {
        if (!$this->session->contains($session)) {
            $this->session[] = $session;
            $session->setCourse($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->session->contains($session)) {
            $this->session->removeElement($session);
            // set the owning side to null (unless already changed)
            if ($session->getCourse() === $this) {
                $session->setCourse(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocument(): Collection
    {
        return $this->document;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->document->contains($document)) {
            $this->document[] = $document;
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->document->contains($document)) {
            $this->document->removeElement($document);
        }

        return $this;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $start_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="sessions")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Course::class, inversedBy="session")
     */
    private $course;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
        }

        return $this;
    }

    public function getCourse(): ?Course
    {
        return $this->course;
    }

    public function setCourse(?Course $course): self
    {
        $this->course = $course;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    private $name;

    private $fullNname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="user")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity=Announcement::class, mappedBy="user")
     */
    private $announcements;

    /**
     * @ORM\ManyToMany(targetEntity=Session::class, mappedBy="user")
     */
    private $sessions;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->announcements = new ArrayCollection();
        $this->sessions = new ArrayCollection();
    }

    public function __toString(){
        return "user";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getFullName(): ?string
    {
        $last_name = $this->last_name;
        $first_name = $this->first_name;
        return $full_name = $last_name . ', ' . $first_name;
  
    }

    public function getName(): ?string
    {
        $last_name = $this->last_name;
        $first_name = $this->first_name;
        return $name = $first_name . ' ' . $last_name;
  
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getAnnouncements(): Collection
    {
        return $this->announcements;
    }

    public function addAnnouncement(Announcement $announcement): self
    {
        if (!$this->announcements->contains($announcement)) {
            $this->announcements[] = $announcement;
            $announcement->setUser($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): self
    {
        if ($this->announcements->contains($announcement)) {
            $this->announcements->removeElement($announcement);
            // set the owning side to null (unless already changed)
            if ($announcement->getUser() === $this) {
                $announcement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addUser($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeUser($this);
        }

        return $this;
    }
}

templates/users_management/_delete_form.html.twig
<form method="post" action="{{ path('users_delete', {id: user.id}) }}" style="height: 32px;"
    onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette personne ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="no-btn pointer"><img class="icon trash" src="{{ asset('icons/trash.svg') }}" alt=""
            title="Supprimer"></button>
</form>

templates/users_management/editUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}&Eacute;diter un utilisateur
{% endblock %}

{% block body %}
	{% include 'nav.html.twig' %}
	<div class="single-row grid-center">
		<div class="">
			<div class="wrap-titles">
				<h2>&Eacute;diter
					{{user.firstName}}
					{{user.lastName}}</h2>
				<h2 class="back-to-dashboard">
					<a href="{{ path('users_management') }}">&#10229; Liste des elèves</a>
				</h2>
			</div>
			<div class="wrap">
				<div class="card">
					{{ form_start(userForm, {'attr': {'class': 'form'} }) }}
					{{ form_row(userForm.first_name) }}
					{{ form_row(userForm.last_name) }}
					{{ form_row(userForm.email) }}
					{{ form_row(userForm.birth_date, {'attr': {'class': 'select-date'} }) }}
					<button class="btn btn-primary-dk">&Eacute;diter</button>
					{{ form_end(userForm) }}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/users_management/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des elèves
{% endblock %}

{% block body %}
{% include 'nav.html.twig' %}
<div class="single-row">
	<div class="">
		<div class="wrap-titles">
			<h2>Liste des elèves</h2>
			<h2 class="back-to-dashboard"><a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a></h2>
		</div>

		<div class="wrap">
			<div class="card p-2">
				<table class="table nowrap display" id="student-table" style="width: 100%">
					<thead>
						<tr>
							<th>Nom</th>
							<th>Prénom</th>
							<th class="text-center">Rôle</th>
							<th>Formation en cours</th>
							<th>Née le</th>
							<th class="text-center">Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for user in users %}
						<tr>
							<td>{{user.lastName}}</td>
							<td>{{user.firstName}}</td>
							<td class="text-center">
								{% if user.roles|length == 2 %}

								<div class="badge-btn">
									<p class="badge">admin</p>
									<a class="" href="{{ path('users_demote', {id: user.id}) }}"
										title="Révoquer les droits administrateurs">&#215;</a>
								</div>
								{% else %}
								<div class="badge-btn role-btn">
									<p class="badge user">elève</p>
									<a href="{{ path('users_promote', {id: user.id}) }}" style="font-size: .6rem">Modifier</a>
								</div>
								{% endif %}

							</td>
							<td>
								{% for session in user.sessions %}
								<span><strong>{{session.course.courseName}}</strong>, <small>du <strong>{{ session.startDate | date("d/m/Y") }}</strong> au <strong>{{ session.endDate | date("d/m/Y") }}</strong></small><br>
								{% else %}
								(Aucune sessions)<br>
								{% endfor %}
								{# <a href="">Gérer</a> #}
							</td>
							<td class="text-center">{{user.birthDate | date("d/m/Y")}}</td>
							<td class="text-center flex">
								<a href="{{ path('users_edit', {id: user.id}) }}" style="height: 32px;"><img
										class="icon edit" src="{{ asset('icons/edit.svg') }}" alt=""
										title="&Eacute;diter"></a>

								{{ include('users_management/_delete_form.html.twig') }}

							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				<a href="{{ path('users_add') }}" type="button" class="btn btn-primary-dk">+ Ajouter un utilisateur</a>
			</div>
		</div>
	</div>
</div>

{% for message in app.flashes('success') %}

<div class="alert success">
	<p>{{ message }}</p>
</div>

{% endfor %}

{% for message in app.flashes('delete') %}

<div class="alert delete">
	<p>{{ message }}</p>
</div>

{% endfor %}

{% for message in app.flashes('edit') %}

<div class="alert edit">
	<p>{{ message }}</p>
</div>

{% endfor %}



<script>
	$(document).ready(function () {
		$('#student-table').DataTable({
			"scrollX": true,
			fixedColumns: true,
			"language": {
				"url": "{{ asset('js/french.lang') }}"
			}
		});
	});
</script>
{% endblock %}

templates/users_management/newUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un utilisateur
{% endblock %}

{% block body %}
{% include 'nav.html.twig' %}
<div class="grid" style="min-height: calc(100vh - 48px - 24px);">

    <div class="">
        <div class="wrap-titles">
            <h2>Ajouter un utilisateur</h2>
            <h2 class="back-to-dashboard"><a href="{{ path('users_management') }}">&#10229; Liste des elèves</a></h2>
        </div>
        <div class="wrap">
            <div class="card">
                {{ form_start(userForm, {'attr': {'class': 'form'} }) }}
                {{ form_row(userForm.email) }}
                {{ form_row(userForm.password) }}
                {{ form_row(userForm.last_name) }}
                {{ form_row(userForm.first_name) }}
                <div>
                    {{ form_label(userForm.sessions) }}
                </div>
                <div class="form-children">
                    {% for session in userForm.sessions %}
                    {{ form_row(session, { 'attr': {'class': 'children'} }) }}
                    {% endfor %}
                </div>
                {{ form_rest(userForm) }}
                <button class="btn btn-primary-dk pointer">Ajouter</button>
                {{ form_end(userForm) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}