src/Entity/Announcement.php
<?php

namespace App\Entity;

use App\Repository\AnnouncementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnnouncementRepository::class)
 */
class Announcement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10000, nullable=true)
     */
    private $announcement_title;

    /**
     * @ORM\Column(type="string", length=50000)
     */
    private $announcement_content;

    /**
     * @ORM\Column(type="date")
     */
    private $announcement_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="announcements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_draft;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnnouncementTitle(): ?string
    {
        return $this->announcement_title;
    }

    public function setAnnouncementTitle(?string $announcement_title): self
    {
        $this->announcement_title = $announcement_title;

        return $this;
    }

    public function getAnnouncementContent(): ?string
    {
        return $this->announcement_content;
    }

    public function setAnnouncementContent(string $announcement_content): self
    {
        $this->announcement_content = $announcement_content;

        return $this;
    }

    public function getAnnouncementDate(): ?\DateTimeInterface
    {
        return $this->announcement_date;
    }

    public function setAnnouncementDate(\DateTimeInterface $announcement_date): self
    {
        $this->announcement_date = $announcement_date;

        return $this;
    }
    
    public function getIsDraft(): ?bool
    {
        return $this->is_draft;
    }
    
    public function setIsDraft(bool $is_draft): self
    {
        $this->is_draft = $is_draft;
        
        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }
    
    public function setUser(?user $user): self
    {
        $this->user = $user;
    
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    private $name;

    private $fullNname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="user")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity=Announcement::class, mappedBy="user")
     */
    private $announcements;

    /**
     * @ORM\ManyToMany(targetEntity=Session::class, mappedBy="user")
     */
    private $sessions;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->announcements = new ArrayCollection();
        $this->sessions = new ArrayCollection();
    }

    public function __toString(){
        return "user";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getFullName(): ?string
    {
        $last_name = $this->last_name;
        $first_name = $this->first_name;
        return $full_name = $last_name . ', ' . $first_name;
  
    }

    public function getName(): ?string
    {
        $last_name = $this->last_name;
        $first_name = $this->first_name;
        return $name = $first_name . ' ' . $last_name;
  
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getAnnouncements(): Collection
    {
        return $this->announcements;
    }

    public function addAnnouncement(Announcement $announcement): self
    {
        if (!$this->announcements->contains($announcement)) {
            $this->announcements[] = $announcement;
            $announcement->setUser($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): self
    {
        if ($this->announcements->contains($announcement)) {
            $this->announcements->removeElement($announcement);
            // set the owning side to null (unless already changed)
            if ($announcement->getUser() === $this) {
                $announcement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addUser($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeUser($this);
        }

        return $this;
    }
}

src/Form/AnnouncementType.php
<?php

namespace App\Form;

use App\Entity\Announcement;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class AnnouncementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('announcement_title')
            ->add('announcement_content', CKEditorType::class, [
                'config_name' => 'announcement_config'
            ])
            ->add('is_draft', CheckboxType::class, [
                'label' => 'Enregistrer comme brouillon',
                'required' => false,
            ])
            ->add('announcement_date', DateType::class, [
                'days' => range(date('d'), 31),
                'months' => range(date('m'), 12),
                'years' => range(date('Y'), date('Y')+100),
            ])
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Announcement::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/AnnouncementController.php
<?php

namespace App\Controller;

use App\Entity\Announcement;
use App\Form\AnnouncementType;
use App\Repository\AnnouncementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/announcement")
 */
class AnnouncementController extends AbstractController
{
    /**
     * @Route("/", name="announcement_index", methods={"GET"})
     */
    public function index(AnnouncementRepository $announcementRepository): Response
    {
        return $this->render('announcement/index.html.twig', [
            'announcements' => $announcementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="announcement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        // guaranty that the user won't be able to access this
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $announcement = new Announcement();
        $form = $this->createForm(AnnouncementType::class, $announcement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            // set the current user as author
            $announcement->setUser($this->getUser());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($announcement);
            $entityManager->flush();
            
            // sends a flash messages for success
            $this->addFlash('success', 'Nouvelle annonce créée');

            return $this->redirectToRoute('announcement_index');
        }

        return $this->render('announcement/new.html.twig', [
            'announcement' => $announcement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="announcement_show", methods={"GET"})
     */
    public function show(Announcement $announcement): Response
    {
        // $this->denyAccessUnlessGranted('ROLE_ADMIN');

        return $this->render('announcement/show.html.twig', [
            'announcement' => $announcement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="announcement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Announcement $announcement): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $form = $this->createForm(AnnouncementType::class, $announcement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Annonce modifiée');

            return $this->redirectToRoute('announcement_index');    
        }
        
        return $this->render('announcement/edit.html.twig', [
            'announcement' => $announcement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="announcement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Announcement $announcement): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        if ($this->isCsrfTokenValid('delete'.$announcement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($announcement);
            $entityManager->flush();
        }

        $this->addFlash('success', 'Annonce supprimée');

        return $this->redirectToRoute('announcement_index');
    }
}

templates/announcement/_card.html.twig
<div class="card">
	<div class="card-header">
		<div><img src="{{ asset('icons/horn.svg') }}" alt=""></div>
		<h4>{{ announcement.announcementTitle}}</h4>
	</div>

	<div class="card-body">
		<small class="mb-1">{{ announcement.announcementDate | date("d/m/Y") }}</small>
		<p>{{ announcement.announcementContent | raw }}</p>
		<small class="mt-1">{{ announcement.user.firstName }}
			{{announcement.user.lastName }}</small>
	</div>
	{% if is_granted('ROLE_ADMIN') %}
		<div class="card-btn">
			<a href="{{ path('announcement_edit', {id: announcement.id}) }}" type="button" class="btn btn-warning btn-sm">&Eacute;diter</a>
			<a href="{{ path('announcement_delete', {id: announcement.id}) }}" type="button" class="btn btn-danger btn-sm">Supprimer</a>
		</div>
	{% endif %}
</div>

templates/announcement/_delete_form.html.twig
<form method="post" action="{{ path('announcement_delete', {'id': announcement.id}) }}" style="height: 32px;"
    onsubmit="return confirm('Souhaitez-vous vraiment supprimer cette annonce ?');" class="pointer">
    
    <input type="hidden" name="_method" value="DELETE">

    <!-- hidden field where the CSRF token is generated -->
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ announcement.id) }}">

    <button class="no-btn"><img class="icon trash" src="{{ asset('icons/trash.svg') }}" alt=""
            title="Supprimer"></button>
</form>

templates/announcement/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form'} }) }}
{{ form_row(form.announcement_title) }}
{{ form_row(form.announcement_content) }}
<div class="form-children option">
	{{ form_row(form.is_draft) }}
</div>
{{ form_row(form.announcement_date, {'attr': {'class': 'select-date'}}) }}

<button class="btn btn-primary-dk">{{ button_label | default('Publier') }}</button>
{{ form_end(form) }}

templates/announcement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}&Eacute;diter une annonce
{% endblock %}

{% block body %}
	{% include 'nav.html.twig' %}

	<div class="single-row">
		<div class="">
			<div class="wrap-titles">
				<h2>&Eacute;diter une annonce</h2>
				<h2 class="back-to-dashboard">
					<a href="{{ path('announcement_index') }}">&#10229; Retour aux annonces</a>
				</h2>
			</div>
			<div class="wrap">
				<div class="card">
					{{ include('announcement/_form.html.twig', {'button_label': 'Enregistrer modifications'}) }}
				</div>
			</div>
		</div>
	</div>


	<a href="">back to list</a>

	{{ include('announcement/_delete_form.html.twig') }}
{% endblock %}

templates/announcement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des annonces
{% endblock %}

{% block body %}
	{% include 'nav.html.twig' %}
	<div class="single-row">
		<div class="">
			<div class="wrap-titles">
				<h2>Gestion des annonces</h2>
				<h2 class="back-to-dashboard">
					{% if is_granted('ROLE_ADMIN') %}
						<a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a>
					{% else %}
						<a href="{{ path('user_dashboard') }}">&#10229; Retour à l'accueil</a>
					{% endif %}
				</h2>
			</div>

			<div class="wrap">
				<div class="card p-2">
					{% if is_granted('ROLE_ADMIN') %}
						<a href="{{ path('announcement_new') }}" class="btn btn-primary-dk mb-1">+ Nouvelle annonce</a>
					{% endif %}

					<table class="table display responsive" id="announcementList" style="width: 100%">
						<thead>
							<tr>

								<th>Date de création</th>
								<th>Titre</th>
								{% if is_granted('ROLE_ADMIN') %}
									<th>Publié</th>
								{% endif %}
								<th>Actions</th>

							</tr>
						</thead>
						<tbody>
							{# for each announcements #}
							{% for announcement in announcements %}
								<tr>
									{# date #}
									<td>{{ announcement.announcementDate ? announcement.announcementDate|date('d M. Y') : '' }}</td>
									{# title #}
									<td>{{ announcement.announcementTitle }}</td>
									{# hidden to user - if published -> check mark #}
									{% if is_granted('ROLE_ADMIN') %}
										<td class="text-center">{{ announcement.isDraft ? '' : '&#10004;' }}</td>
									{% endif %}
									<td
										class="flex">
										{# see announcement #}
										<a href="{{ path('announcement_show', {'id': announcement.id}) }}">Voir</a>
										{# hidden to user #}
										{% if is_granted('ROLE_ADMIN') %}
											{# edit announcement #}
											<a href="{{ path('announcement_edit', {'id': announcement.id}) }}" style="height: 32px;">
												<img class="icon edit" src="{{ asset('icons/edit.svg') }}" alt="" title="&Eacute;diter">
											</a>
											{# include delete form #}
											{{ include('announcement/_delete_form.html.twig') }}
										{% endif %}
									</td>
								</tr>
							{% else %}
								{# if no announcements #}
								<tr>
									<td colspan="4">Aucune annonce</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>

				</div>
			</div>
		</div>
	</div>

	{% for message in app.flashes('success') %}

		<div class="alert success">
			<p>{{ message }}</p>
		</div>

	{% endfor %}

	{% for message in app.flashes('delete') %}

		<div class="alert delete">
			<p>{{ message }}</p>
		</div>

	{% endfor %}

	{% for message in app.flashes('edit') %}

		<div class="alert edit">
			<p>{{ message }}</p>
		</div>

	{% endfor %}

	<script>
		$(document).ready(function () {
$('#announcementList').DataTable({
// "scrollX": true,
// fixedColumns: true,
"order": 
[0, 'desc']
,
"language": {
"url": "{{ asset('js/french.lang') }}"
}
});
});
	</script>
{% endblock %}

templates/announcement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publier une nouvelle annonce{% endblock %}

{% block body %}
{% include 'nav.html.twig'%}

<div class="single-row">
    <div class="">
        <div class="wrap-titles">
            <h2>Publier une nouvelle annonce</h2>
            <h2 class="back-to-dashboard"><a href="{{ path('document_index') }}">&#10229; Retour aux documents</a></h2>
        </div>
        <div class="wrap">
            <div class="card">

                {{ include('announcement/_form.html.twig', {'button_label': 'Publier'}) }}

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/announcement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce{% endblock %}

{% block body %}
{% include 'nav.html.twig' %}
<div class="single-row" style="place-content: center;">
    <div class="">
        <div class="wrap-titles">
            <h2>Annonce -
                {% if is_granted('ROLE_ADMIN') %}
                {{ announcement.isDraft ? 'Publié : &#x292B;' : 'Publié : &#10004;' }}
                {% endif %}


            </h2>
            <h2 class="back-to-dashboard">
                {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a>
                {% else %}
                <a href="{{ path('user_dashboard') }}">&#10229; Retour à l'accueil</a>
                {% endif %}
            </h2>

        </div>

        <div class="wrap">
            {% include "announcement/_card.html.twig" %}
        </div>
    </div>
</div>
{# {{ include('announcement/_delete_form.html.twig') }} #}
{% endblock %}