src/Entity/Course.php
<?php

namespace App\Entity;

use App\Entity\Session;
use App\Entity\Document;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CourseRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=CourseRepository::class)
 */
class Course
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $course_name;

    /**
     * @ORM\OneToMany(targetEntity=Session::class, mappedBy="course")
     */
    private $session;

    /**
     * @ORM\ManyToMany(targetEntity=document::class, inversedBy="courses")
     */
    private $document;

    public function __construct()
    {
        $this->session = new ArrayCollection();
        $this->document = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCourseName(): ?string
    {
        return $this->course_name;
    }

    public function setCourseName(string $course_name): self
    {
        $this->course_name = $course_name;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSession(): Collection
    {
        return $this->session;
    }

    public function addSession(Session $session): self
    {
        if (!$this->session->contains($session)) {
            $this->session[] = $session;
            $session->setCourse($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->session->contains($session)) {
            $this->session->removeElement($session);
            // set the owning side to null (unless already changed)
            if ($session->getCourse() === $this) {
                $session->setCourse(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocument(): Collection
    {
        return $this->document;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->document->contains($document)) {
            $this->document[] = $document;
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->document->contains($document)) {
            $this->document->removeElement($document);
        }

        return $this;
    }
}

src/Entity/Document.php
<?php

namespace App\Entity;

use App\Entity\Course;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\DocumentRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file_name;

    /**
     * @ORM\Column(type="string", length=10000, nullable=true)
     */
    private $file_desc;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $file_size;

    /**
     * @ORM\ManyToMany(targetEntity=Course::class, mappedBy="document")
     */
    private $courses;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    public function __construct()
    {
        $this->courses = new ArrayCollection();
    }

    public function __toString()
    {
        return "ok";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getFileDesc(): ?string
    {
        return $this->file_desc;
    }

    public function setFileDesc(?string $file_desc): self
    {
        $this->file_desc = $file_desc;

        return $this;
    }

    public function getFileSize(): ?int
    {
        return $this->file_size;
    }

    public function setFileSize(?int $file_size): self
    {
        $this->file_size = $file_size;

        return $this;
    }

    /**
     * @return Collection|Course[]
     */
    public function getCourses(): Collection
    {
        return $this->courses;
    }

    public function addCourse(Course $course): self
    {
        if (!$this->courses->contains($course)) {
            $this->courses[] = $course;
            $course->addDocument($this);
        }

        return $this;
    }

    public function removeCourse(Course $course): self
    {
        if ($this->courses->contains($course)) {
            $this->courses->removeElement($course);
            $course->removeDocument($this);
        }

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Course;
use App\Entity\Document;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('file_url')
            ->add('file_name', TextType::class, [
                'required' => true,
            ])
            ->add('file_desc', TextareaType::class, [
                'required' => false,
            ])
            ->add('file', FileType::class, [
                'label' => 'Document',
                'required' => true,
                'data_class' => null,
                // 'constraints' => [
                //     new File([
                //         'maxSize' => '1024k',
                //         'mimeTypes' => [
                //             'application/pdf',
                //             'application/x-pdf',
                //         ],
                //         'mimeTypesMessage' => 'Please upload a valid PDF document',
                //     ])
            ])
            // ->add('file_size')
            ->add('courses', EntityType::class, [
                'class' => Course::class,
                'choice_label' => function ($course) {
                    return $course->getCourseName();
                },
                'multiple' => true,
                'expanded' => true,
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
            'translation_domain' => 'forms',
        ]);
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Entity\User;
use App\Form\DocumentType;
use App\Repository\CourseRepository;
use App\Repository\DocumentRepository;
use App\Repository\SessionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
 * @Route("/document")
 */
class DocumentController extends AbstractController
{
    /**
     * @Route("/", name="document_index")
     */
    public function index(SessionRepository $sessionRepo, DocumentRepository $documentRepository, CourseRepository $courseRepository): Response
    {
        $sessions = $this->getUser()->getSessions();
       
        
        $files = [];
        $i=0;
        
        foreach($sessions as $session) {
            foreach($session->getCourse()->getDocument() as $document){
                $files[$i] = $document;
                $i++;
            }
           
            
        }
        // a mettre le $files dans le return pour le twig et le parcourir dans le twig
        // dump($files);
        // $files = $documentRepository->getUsersDocuments($user->getId());



        $documents = $documentRepository->findAll();
        if ($documents) {
            foreach ($documents as $document) {
                $courses = $courseRepository->find($document->getId());
            }
        } else {
            $courses = null;
        }

        

        return $this->render('document/index.html.twig', [
            'documents' => $documents,
            'courses' => $courses,
        ]);
    }

    /**
     * @Route("/new", name="document_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $newDocument = new Document();
        $form = $this->createForm(DocumentType::class, $newDocument);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();

            /** @var UploadedFile $documentFile */
            $documentFile = $form->get('file')->getData();

            // this condition is needed because the 'document' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($documentFile) {
                // $originalFilename = pathinfo($documentFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                // $safeFilename = $slugger->slug($originalFilename);
                $safeFilename = 'doc';
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $documentFile->guessExtension();

                // Move the file to the directory where documents are stored
                try {
                    $documentFile->move(
                        $this->getParameter('documentDir'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                // updates the 'documentFilename' property to store the PDF file name
                // instead of its contents
                $newDocument->setFileName($newFilename);

            }
            
            // ... persist the $document variable or any other work
            $courses = $form->get('courses')->getData();
            $entityManager->persist($newDocument);

            foreach ($courses as $course) {
                $course->addDocument($newDocument);
                $entityManager->persist($course);
            };
            
            $entityManager->flush();

            $this->addFlash('success', 'Document ajouté');

            return $this->redirectToRoute('document_index');
        }

        return $this->render('document/new.html.twig', [
            'document' => $newDocument,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="document_show", methods={"GET"})
     */
    public function show(Document $document): Response
    {
        return $this->render('document/show.html.twig', [
            'document' => $document,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="document_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Document $document): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('edit', 'Document édité');

            return $this->redirectToRoute('document_index');
        }

        return $this->render('document/edit.html.twig', [
            'document' => $document,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="document_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Document $document): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        if ($this->isCsrfTokenValid('delete' . $document->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($document);
            $entityManager->flush();
        }
        $this->addFlash('delete', 'Document supprimé');

        return $this->redirectToRoute('document_index');
    }
}

templates/document/_delete_form.html.twig
<form method="post" action="{{ path('document_delete', {'id': document.id}) }}" style="height: 32px;"
    onsubmit="return confirm('&Ecirc;tes-vous s&ucirc;r de vouloir supprimer ce fichier ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ document.id) }}">
    <button class="no-btn"><img class="icon trash" src="{{ asset('icons/trash.svg') }}" alt="" title="Supprimer"></button>
</form>

templates/document/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form'} }) }}
{{ form_row(form.file_name) }}
{{ form_row(form.file_desc) }}
{{ form_row(form.file) }}
<div>
	{{ form_label(form.courses) }}
</div>
<div class="form-children">
	{% for course in form.courses %}
		{{ form_row(course, { 'attr': {'class': 'children'} }) }}
	{% endfor %}
</div>
{{ form_rest(form) }}
<button class="btn btn-primary-dk">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/document/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Document{% endblock %}

{% block body %}
{% include 'nav.html.twig'%}

<div class="single-row">
    <div class="">
        <div class="wrap-titles">
            <h2>&Eacute;diter {{ document.fileName }}</h2>
            <h2 class="back-to-dashboard"><a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a></h2>
        </div>
        <div class="wrap">
            <div class="card">

                {{ include('document/_form.html.twig', {'button_label': 'Update'}) }}

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/document/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des documents
{% endblock %}

{% block body %}
{% include 'nav.html.twig'%}
<div class="single-row">
	<div class="">
		<div class="wrap-titles">
			<h2>Liste des fichiers</h2>
			<h2 class="back-to-dashboard"><a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a></h2>
		</div>
		<div class="wrap">
			<div class="card p-2">

				<table class="table display" id="documentList" style="width: 100%">
					<thead>
						<tr>
							<th>Nom</th>
							<th>Description</th>
							<th>Taille</th>
							<th>Disponibilité(s)</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>

						{% for document in documents %}
						<tr>
							<td>{{ document.fileName }}</td>
							<td>{{ document.fileDesc }}</td>
							<td>{{ document.fileSize }}</td>
							<td>
								{% for course in document.courses %}
								{{ course.courseName }}<br>

								{% endfor %}
							</td>
							<td class="flex">
								<a href="{{ asset('documents/' ~ document.fileName) }}">Télécharger</a>
								{% if is_granted('ROLE_ADMIN') %}

								<a href="{{ path('document_edit', {'id': document.id}) }}" style="height: 32px;">
									<img class="icon edit" src="{{ asset('icons/edit.svg') }}" alt=""
										title="&Eacute;diter"></a>
								{{ include('document/_delete_form.html.twig') }}
								{% endif %}
							</td>
						</tr>

						{% else %}
						<tr>
							<td colspan="5">Aucun fichier(s)</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% if is_granted('ROLE_ADMIN') %}
				<a href="{{ path('document_new') }}" class="btn btn-primary-dk">+ Nouveau fichier</a>
				{% endif %}

			</div>
		</div>
	</div>
</div>
{% for message in app.flashes('success') %}

<div class="alert success">
	<p>{{ message }}</p>
</div>

{% endfor %}

{% for message in app.flashes('delete') %}

<div class="alert delete">
	<p>{{ message }}</p>
</div>

{% endfor %}

{% for message in app.flashes('edit') %}

<div class="alert edit">
	<p>{{ message }}</p>
</div>

{% endfor %}
<script>
	$(document).ready(function () {
		$('#documentList').DataTable({
			"scrollX": true,
			fixedColumns: true,
			"language": {
				"url": "{{ asset('js/french.lang') }}"
			},

		});
	});
</script>
{% endblock %}

templates/document/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Document{% endblock %}

{% block body %}
{% include 'nav.html.twig'%}

<div class="single-row">
    <div class="">
        <div class="wrap-titles">
            <h2>Liste des sessions</h2>
            <h2 class="back-to-dashboard"><a href="{{ path('document_index') }}">&#10229; Retour aux documents</a></h2>
        </div>
        <div class="wrap">
            <div class="card">

                {{ include('document/_form.html.twig') }}

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/document/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Document{% endblock %}

{% block body %}
    <h1>Document</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ document.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ document.fileName }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ document.fileDesc }}</td>
            </tr>
            <tr>
                <th>Taille</th>
                <td>{{ document.fileSize }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('document_index') }}">back to list</a>

    <a href="{{ path('document_edit', {'id': document.id}) }}">edit</a>

    {{ include('document/_delete_form.html.twig') }}
{% endblock %}