src/Entity/Course.php
<?php

namespace App\Entity;

use App\Entity\Session;
use App\Entity\Document;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CourseRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=CourseRepository::class)
 */
class Course
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $course_name;

    /**
     * @ORM\OneToMany(targetEntity=Session::class, mappedBy="course")
     */
    private $session;

    /**
     * @ORM\ManyToMany(targetEntity=document::class, inversedBy="courses")
     */
    private $document;

    public function __construct()
    {
        $this->session = new ArrayCollection();
        $this->document = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCourseName(): ?string
    {
        return $this->course_name;
    }

    public function setCourseName(string $course_name): self
    {
        $this->course_name = $course_name;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSession(): Collection
    {
        return $this->session;
    }

    public function addSession(Session $session): self
    {
        if (!$this->session->contains($session)) {
            $this->session[] = $session;
            $session->setCourse($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->session->contains($session)) {
            $this->session->removeElement($session);
            // set the owning side to null (unless already changed)
            if ($session->getCourse() === $this) {
                $session->setCourse(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocument(): Collection
    {
        return $this->document;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->document->contains($document)) {
            $this->document[] = $document;
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->document->contains($document)) {
            $this->document->removeElement($document);
        }

        return $this;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $start_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="sessions")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Course::class, inversedBy="session")
     */
    private $course;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
        }

        return $this;
    }

    public function getCourse(): ?Course
    {
        return $this->course;
    }

    public function setCourse(?Course $course): self
    {
        $this->course = $course;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    private $name;

    private $fullNname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="user")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity=Announcement::class, mappedBy="user")
     */
    private $announcements;

    /**
     * @ORM\ManyToMany(targetEntity=Session::class, mappedBy="user")
     */
    private $sessions;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->announcements = new ArrayCollection();
        $this->sessions = new ArrayCollection();
    }

    public function __toString(){
        return "user";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getFullName(): ?string
    {
        $last_name = $this->last_name;
        $first_name = $this->first_name;
        return $full_name = $last_name . ', ' . $first_name;
  
    }

    public function getName(): ?string
    {
        $last_name = $this->last_name;
        $first_name = $this->first_name;
        return $name = $first_name . ' ' . $last_name;
  
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getAnnouncements(): Collection
    {
        return $this->announcements;
    }

    public function addAnnouncement(Announcement $announcement): self
    {
        if (!$this->announcements->contains($announcement)) {
            $this->announcements[] = $announcement;
            $announcement->setUser($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): self
    {
        if ($this->announcements->contains($announcement)) {
            $this->announcements->removeElement($announcement);
            // set the owning side to null (unless already changed)
            if ($announcement->getUser() === $this) {
                $announcement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addUser($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeUser($this);
        }

        return $this;
    }
}

templates/sessions_management/editSession.html.twig
{% extends 'base.html.twig' %}

{% block title %}&Eacute;diter
{{session.course.courseName}}
{% endblock %}

{% block body %}
{% include 'nav.html.twig' %}
<div class="single-row">
	<div class="">
		<div class="wrap-titles">
			<h2>&Eacute;diter
				{{session.course.courseName}}</h2>
			<h2 class="back-to-dashboard"><a href="{{ path('sessions_management') }}">&#10229; Retour aux sessions</a></h2>
		</div>
		<div class="wrap">
			<div class="grid-row" style="display: grid">
			<div class="card">
				<div class="card-header">
					<div><img src="{{ asset('icons/edit-lg.svg') }}" alt=""></div>
					<h4>Modifier la session</h4>
				</div>
				<div class="card-body">
					{{ form_start(sessionForm, {'attr': {'class': 'form'} }) }}
					{{ form_row(sessionForm.start_date, {'attr': {'class': 'select-date'}})}}
					{{ form_row(sessionForm.end_date, {'attr': {'class': 'select-date'}})}}
					{{ form_row(sessionForm.course) }}
					<button class="btn btn-primary-dk" type="submit">Modifier</button>
					{{ form_end(sessionForm) }}
				</div>
			</div>

			<div class="card">
				<div class="card-header">
					<div><img src="{{ asset('icons/user-edit.svg') }}" alt=""></div>
					<h4>Liste des elèves</h4>
				</div>
				<div class="card-body">
					<table id="sessionUsersList" class="table  display">
						<thead>
							<tr>
								<th>Nom, Prénom</th>
								<th class="text-center">Enlever</th>
							</tr>
						</thead>
						<tbody>
							{% for user in session.user %}
							<tr>
								<td>{{user.fullName}}</td>
								<td class="text-center">
									<a href="{{ path('sessions_remove_user', {user: user.id, session: session.id}) }}"
										class="del-link"><img src="{{ asset('icons/delete.svg') }}" alt="" style="width: 16px;"></a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>

				</div>
			</div>
		</div>

			<div class="grid-row">


				<div class="card">
					<div class="card-header">
						<div><img src="{{ asset('icons/user-edit.svg') }}" alt=""></div>
						<h4>Ajouter des elèves</h4>
					</div>
					<div class="card-body">
						<table id="userList" class="table compact display">
							<thead>
								<tr>
									<th>Nom, Prénom</th>
									<th class="text-center">Ajouter</th>
								</tr>
							</thead>
							<tbody>
								{% for user in users %}
								<tr>
									<td>{{user.fullName}}</td>
									<td class="text-center">
										{% set inSession = "" %}
										{% for sessions in user.sessions %}
										{% if session.id == sessions.id %}
										{% set inSession = true %}
										{% endif %}
										{% endfor %}
										{% if inSession == true %}
										<button type="button" class="btn btn-gray-dk" disabled style="width: 85px;">
											Déjà inscrit</button>
										{% else %}
										<a href="{{ path('sessions_add_user', {user: user.id, session: session.id}) }}"
											type="button" class="btn btn-warning" style="width: 61px;">+
											Ajouter</a>
										{% endif %}
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% for message in app.flashes('success') %}

<div class="alert success">
	<p>{{ message }}</p>
</div>

{% endfor %}

{% for message in app.flashes('delete') %}

<div class="alert delete">
	<p>{{ message }}</p>
</div>

{% endfor %}

{% for message in app.flashes('edit') %}

<div class="alert edit">
	<p>{{ message }}</p>
</div>

{% endfor %}
<script>
	$(document).ready(function () {
		$('#userList').DataTable({
			fixedColumns: true,
			"language": {
				"url": "{{ asset('js/french.lang') }}"
			},

		});
		$('#sessionUsersList').DataTable({
			fixedColumns: true,
			"language": {
				"url": "{{ asset('js/french.lang') }}"
			},

		});
	});
</script>
{% endblock %}

templates/sessions_management/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des sessions des formations
{% endblock %}

{% block body %}
{% include 'nav.html.twig'%}

<div class="wrap-grid mobile-grid">
	<div class="sessions-list-wrap">
		<div class="">
			<div class="wrap-titles">
				<h2>Liste des sessions</h2>
				<h2 class="back-to-dashboard"><a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a></h2>
			</div>
			<div class="wrap">
				<div class="card" style="padding: 24px">
					<table class="table nowrap display" id="sessions-table">
						<thead>
							<tr>
								<th>Date de début</th>
								<th>Date de fin</th>
								<th>Nom de la formation</th>
								<th>Liste des elèves</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for session in sessions %}
							<tr>
								<td class="text-center">{{session.startDate | date("d/m/Y")}}</td>
								<td class="textcenter">{{session.endDate | date("d/m/Y")}}</td>
								<td>{{session.course.courseName}}</td>
								<td>
									<span data-index={{session.id}}	class="collapse-btn pointer">Liste des apprenants
										<svg width="1em" height="1em" viewbox="0 0 16 16" class="bi bi-caret-down-fill"
											fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path
												d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
										</svg>
									</span>

									<ul class="collapse" id="session{{session.id}}UsersList" data-index="{{session.id}}">
										{% for user in session.user %}
										<li>{{user.firstName}} {{user.lastName}}</li>
										{% endfor %}
									</ul>

								</td>
								<td>
									<a href="{{ path('sessions_edit', {id: session.id}) }}"><img class="icon edit"
											src="{{ asset('icons/edit.svg') }}" alt="" title="&Eacute;diter"></a>
									<a href="{{ path('sessions_delete', {id: session.id}) }}"><img class="icon trash"
											src="{{ asset('icons/trash.svg') }}" alt="" title="Supprimer"></a>
								</td>
							</tr>
							{% endfor %}

						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="new-session-wrap">
		<div class="">
			<div class="wrap-titles">
				<h2>Ajouter une session</h2>
				<h2 class="back-to-dashboard"><a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a></h2>
			</div>
			<div class="wrap">
				<div class="card">
					{{ form_start(sessionForm, {'attr': {'class': 'form'} }) }}
					{{ form_row(sessionForm.course) }}
					{{ form_row(sessionForm.start_date, {'attr': {'class': 'select-date'}})}}
					{{ form_row(sessionForm.end_date, {'attr': {'class': 'select-date'}})}}
					<button class="btn btn-primary-dk" type="submit">Ajouter</button>
					{{ form_end(sessionForm) }}
				</div>
			</div>
		</div>
	</div>
	<div class="new-course-wrap">
		<div class="">
			<div class="wrap-titles">
				<h2>Ajouter un module</h2>
				<h2 class="back-to-dashboard"><a href="{{ path('admin') }}">&#10229; Retour à l'accueil</a></h2>
			</div>
			<div class="wrap">
				<div class="card">
					{{ form_start(courseForm, {'attr': {'class': 'form'} }) }}
					{{ form_rest(courseForm) }}
					<button class="btn btn-primary-dk" type="submit">Ajouter</button>
					{{ form_end(courseForm) }}
				</div>
			</div>
		</div>
	</div>
	{% for message in app.flashes('success') %}

	<div class="alert success">
		<p>{{ message }}</p>
	</div>

	{% endfor %}

	{% for message in app.flashes('delete') %}

	<div class="alert delete">
		<p>{{ message }}</p>
	</div>

	{% endfor %}

	{% for message in app.flashes('edit') %}

	<div class="alert edit">
		<p>{{ message }}</p>
	</div>

	{% endfor %}

	<script>
		$(document).ready(function () {
			$('#sessions-table').DataTable({
				// "scrollX": true,
				fixedColumns: true,
				"language": {
					"url": "{{ asset('js/french.lang') }}"
				},
			});

			$('.collapse-btn').click(function () {
				index = $(this).data('index');
				$('.collapse[data-index =' + index + ']').toggleClass('expanded');
				console.log(index);
			})
		});
	</script>
	{% endblock %}